"use client"
import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";
import { useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "PlanetGuessr",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useEffect(()=> {

    if (typeof window !== 'undefined') {
      require('aframe');
    }

  }, [])

  return (
    <html lang="en">
      <head>
        <Script src="/elipse.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* <Script src="/script.js" strategy="afterInteractive" /> */}
      </body>
    </html>
  );
}
